config/routes.rb
Rails.application.routes.draw do
  root 'pages#home_page'
  get 'about'=> 'pages#about_page'
  get 'contact'=> 'pages#contact_page'
  get 'dashboard'=> 'pages#dashboard_page'
  get 'cart'=> 'pages#cart_page'
  get 'product' => 'pages#product_page'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home_page
    @title ="Home Page"
  end

  def about_page
    @title ="About Page"

  end

  def contact_page
    @title ="Contact Page"

  end

  def dashboard_page
    @title ="Dashboard Page"

  end

  def cart_page
    @title ="Cart Page"

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecomm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about_page.html.erb
<h1><%= @title%></h1>
<p>Find me in app/views/pages/about_page.html.erb</p>

app/views/pages/cart_page.html.erb
<h1><%= @title%></h1>
<p>Find me in app/views/pages/cart_page.html.erb</p>

app/views/pages/contact_page.html.erb
<h1><%= @title%></h1>
<p>Find me in app/views/pages/contact_page.html.erb</p>

app/views/pages/dashboard_page.html.erb
<h1><%= @title%></h1>
<p>Find me in app/views/pages/dashboard_page.html.erb</p>

app/views/pages/home_page.html.erb
<h1><%= @title%></h1>
<p>Find me in app/views/pages/home_page.html.erb</p>
<%= render partial: 'shared/links' %>

app/views/shared/_links.html.erb
<%= link_to "About",about_path%>
<%= link_to "Cart", cart_path%>
<%= link_to "Dashboard",dashboard_path%>
<%= link_to "Home",root_path%>
<%= link_to "Contact",contact_path%>